//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RollOnBlbEntities : DbContext
    {
        public RollOnBlbEntities()
            : base("name=RollOnBlbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adhesion> Adhesion { get; set; }
        public virtual DbSet<Caroussel> Caroussel { get; set; }
        public virtual DbSet<Forum> Forum { get; set; }
        public virtual DbSet<Galerie> Galerie { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Newsletter> Newsletter { get; set; }
        public virtual DbSet<Panneau> Panneau { get; set; }
        public virtual DbSet<Partenaire> Partenaire { get; set; }
        public virtual DbSet<Participation> Participation { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<PublicationImage> PublicationImage { get; set; }
        public virtual DbSet<Sport> Sport { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<TypeGalerie> TypeGalerie { get; set; }
        public virtual DbSet<TypePublication> TypePublication { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
