//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caroussel
    {
        public int idCaroussel { get; set; }
        public byte visibleCaroussel { get; set; }
        public string urlminiCaroussel { get; set; }
        public string urlCaroussel { get; set; }
        public string altCaroussel { get; set; }
    }
}
