//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forum()
        {
            this.Message = new HashSet<Message>();
        }
    
        public int idForum { get; set; }
        public System.DateTime datePostForum { get; set; }
        public Nullable<int> populariteForum { get; set; }
        public string ThemeForum { get; set; }
        public string SujetForum { get; set; }
        public Nullable<int> idMedia { get; set; }
        public Nullable<int> idSport { get; set; }
        public int idUtilisateur { get; set; }
        public int idStatut { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
    }
}
