//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galerie
    {
        public int idGalerie { get; set; }
        public Nullable<System.DateTime> datePostGalerie { get; set; }
        public Nullable<int> idSport { get; set; }
        public string urlGalerie { get; set; }
        public string AltGalerie { get; set; }
        public string nomGalerie { get; set; }
        public Nullable<int> ordreGalerie { get; set; }
        public int idStatut { get; set; }
        public int idTypeGalerie { get; set; }
        public byte visibleGalerie { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual TypeGalerie TypeGalerie { get; set; }
    }
}
