//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int idMessage { get; set; }
        public string texteMessage { get; set; }
        public int idForum { get; set; }
        public int idStatut { get; set; }
        public int idUtilisateur { get; set; }
        public Nullable<int> idMedia { get; set; }
        public Nullable<int> idSport { get; set; }
        public Nullable<int> populariteMessage { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
