//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public int idNewsletter { get; set; }
        public string titreNewsletter { get; set; }
        public string sousTitreNewsletter { get; set; }
        public string contenuNewsletter { get; set; }
        public int idUtilisateur { get; set; }
        public Nullable<int> idMedia { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
