//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partenaire
    {
        public int idPartenaire { get; set; }
        public string nomPartenaire { get; set; }
        public string urlPartenaire { get; set; }
        public string lienPartenaire { get; set; }
        public string altPartenaire { get; set; }
        public Nullable<int> OrdrePartenaire { get; set; }
        public byte visiblePartenaire { get; set; }
    }
}
