//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Roll_On_Blb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Forum = new HashSet<Forum>();
            this.Message = new HashSet<Message>();
            this.Newsletter = new HashSet<Newsletter>();
            this.Publication = new HashSet<Publication>();
        }
    
        public int idUtilisateur { get; set; }
        public string mailUtilisateur { get; set; }
        public string pseudoUtilisateur { get; set; }
        public string nomUtilisateur { get; set; }
        public string prenomUtilisateur { get; set; }
        public Nullable<System.DateTime> DateNaissanceUtilisateur { get; set; }
        public string mdpUtilisateur { get; set; }
        public System.DateTime dateInscriptionUtilisateur { get; set; }
        public string tokenUtilisateur { get; set; }
        public Nullable<int> idAdhesion { get; set; }
        public int idStatut { get; set; }
        public Nullable<int> idSport { get; set; }
    
        public virtual Adhesion Adhesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forum> Forum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Newsletter> Newsletter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publication { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual Statut Statut { get; set; }
    }
}
